package dyvil.tools.compiler.phase;

import java.util.Collection;

import dyvil.io.FileUtils;
import dyvil.tools.compiler.DyvilCompiler;
import dyvil.tools.compiler.ast.structure.ICompilationUnit;
import dyvil.tools.compiler.backend.ClassWriter;
import dyvil.tools.compiler.config.CompilerConfig;
import dyvil.tools.compiler.lexer.Dlex;
import dyvil.tools.compiler.lexer.token.Token;
import dyvil.tools.compiler.util.TestThread;

public interface ICompilerPhase extends Comparable<ICompilerPhase>
{
	/**
	 * Splits the input file into {@link Token Tokens} using {@link Dlex}.
	 */
	ICompilerPhase	TOKENIZE		= new ParallelCompilerPhase(10, "TOKENIZE", ICompilationUnit::tokenize);
	
	/**
	 * Parses the list of tokens generated by {@link #TOKENIZE}.
	 */
	ICompilerPhase	PARSE			= new ParallelCompilerPhase(20, "PARSE", ICompilationUnit::parse);
	
	/**
	 * Resolves packages, classes and types.
	 */
	ICompilerPhase	RESOLVE_TYPES	= new ParallelCompilerPhase(30, "RESOLVE_TYPES", ICompilationUnit::resolveTypes);
	
	/**
	 * Resolves methods and field names.
	 */
	ICompilerPhase	RESOLVE			= new ParallelCompilerPhase(40, "RESOLVE", ICompilationUnit::resolve);
	
	/**
	 * Checks for semantical errors.
	 */
	ICompilerPhase	CHECK			= new ParallelCompilerPhase(50, "CHECK", ICompilationUnit::check);
	
	/**
	 * Prints the AST.
	 */
	ICompilerPhase	PRINT			= new ParallelCompilerPhase(60, "PRINT", unit -> DyvilCompiler.logger.info(unit.getInputFile() + ":\n" + unit.toString()));
	
	/**
	 * Saves the formatted AST to the input file
	 */
	ICompilerPhase	FORMAT			= new ParallelCompilerPhase(70, "FORMAT", unit -> FileUtils.write(unit.getInputFile(), unit.toString()));
	
	/**
	 * Folds constants.
	 */
	ICompilerPhase	FOLD_CONSTANTS	= new FoldConstants(80);
	
	/**
	 * Compiles the AST to byte code and stores the generated .class files in
	 * the bin directory.
	 */
	ICompilerPhase	COMPILE			= new ParallelCompilerPhase(90, "COMPILE", unit -> unit.compile());
	
	/**
	 * Converts the .class files in the bin directory to a JAR file, sets up the
	 * classpath and signs the JAR.
	 */
	ICompilerPhase	JAR				= new CompilerPhase(100, "JAR", units -> ClassWriter.generateJAR(DyvilCompiler.files));
	
	/**
	 * Tests the main type specified in {@link CompilerConfig#mainType}.
	 */
	ICompilerPhase	TEST			= new CompilerPhase(110, "TEST", units -> new TestThread().start());
	
	public String getName();
	
	public int getID();
	
	public void apply(Collection<ICompilationUnit> units);
}
