#!/usr/bin/env bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
DYVIL_HOME=$DIR/..
java -Xbootclasspath/a:$DYVIL_HOME/lib/dyvil-compiler.jar -Xbootclasspath/a:$DYVIL_HOME/lib/dyvil-library.jar -jar $DYVIL_HOME/lib/dyvil-repl.jar "$@"
